### ISSUE TITLE
PINGClient from mctools returning NoneType

### ISSUE THREAD

**Issue by guerreromets** [0n1udra/slime_server#1]
https://github.com/0n1udra/slime_server/blob/adb41ba17be71434ffd6b202b43e437f82d71264/source/discord_mc_bot.py#L769

PINGClient from mctools returning NoneType
Looks like after previous update the version number isnt returning right
it messes with starting the server

**Comment by 0n1udra** [comment]
I am trying to simplify and improve the bot when using RCON features. I think I fixed the issue that you were having, The bot should now handle connection errors or when RCON server is just unreachable now. Let me know if that did it.
