### ISSUE TITLE
Suggestion - Being able to create and delete servers from the bot

### ISSUE THREAD

**Issue by Dycool** [0n1udra/slime_server#10]
Would be cool if we were able to create servers or even delete them in discord, would really automate things.

**Comment by 0n1udra** [comment]
Good idea. I started working on it today, should be done fairly soon.

**Comment by Dycool** [comment]
And it would be nice if it automatically connected with a proxy, so it would not need to do any port forwarding more than it needs to.

**Comment by 0n1udra** [comment]
Not sure what you mean exactly. Could you elaborate.

**Comment by Dycool** [comment]
Like automatically connect to a bungeecord proxy or something, Im not sure if the bot allows multiple server management.

**Comment by 0n1udra** [comment]
I don't know anything about BungeeCord, that might be something I could look into in the future.
