### ISSUE TITLE
Xp command giving error.

### ISSUE THREAD

**Issue by Dycool** [0n1udra/slime_server#11]
[10:58:53 INFO]: Incorrect argument for command
[10:58:53 INFO]: xp 0.7469874118303291<--[HERE]

paper 1.19.2

**Comment by 0n1udra** [comment]
That's on purpose. It's my backhanded way to test if the server is active and reachable. I couldn't think of an easier method than sending a command with a unique code, then checking the logs for said code. I mean I could use ping, but I think this is faster. I'm planning on adding an option to disable or change the method of checking server status. As far as I can tell, it doesn't affect the server in any ways  other than cluttering the logs.
