### ISSUE TITLE
I am new to WSL and Python and have a question.

### ISSUE THREAD

**Issue by BellCocoa** [0n1udra/slime_server#12]
I changed variables as configured and installed the python module, but it doesn't work.
I'll put up the error log.
[https://pastebin.com/x0xa1v8J](url)
This text uses translations.

**Comment by 0n1udra** [comment]
sorry for late reply. 

a possible workaround for now would be to manually set the username. 
i.e.
`user = 'USER'`
also make sure all the path variables that use `user` variable are set correctly too.
