### ISSUE TITLE
"can't find window 1"

### ISSUE THREAD

**Issue by Zoxsage** [0n1udra/slime_server#2]
Hello, when I try to run the bot with tmux, I have a message "Can't find window 1". I don't understand why, so if anyone has a solution I'm interested ! And when I try to run discord_mc_bot I have this msg : "can't find session: mcserver". I hope someone has a solution, thanks !

**Comment by 0n1udra** [comment]
I will check on that. Does the bot work at all if you disable tmux in alime_vars?

**Comment by HDProduction010** [comment]
I had this same issue when I ran the command above it just took me to a bashed panel. I assume this is what it is supposed to do but the error code still just showed "Can't find window 1".

**Comment by 0n1udra** [comment]
Sorry for the late replay! I think I fixed it. It was because of me having a different tmux config, so the code I wrote was specific for my setup, mb.... It should work fine now if you get the 5.1 release. 
https://github.com/0n1udra/slime_server/releases/tag/v5.1

**Comment by HDProduction010** [comment]
Perfect that worked.
