### ISSUE TITLE
??QUESTION??

### ISSUE THREAD

**Issue by gamingoninsulin** [0n1udra/slime_server#9]
i get some awefull of errors but when i check with pycharm no errors are thrown before i run : RUN_BOT.py this are my errors

![pycharm error Slime_Server py DiscordBot](https://user-images.githubusercontent.com/59486309/185414218-1cc340ec-4f31-4585-950d-22a2b83b6a14.JPG)

**Comment by gamingoninsulin** [comment]
here a photo with no errors shown by pycharm a i gent only hte errors above when running RUN_BOT.py shown above here

![noerrors pycharm dicrod bot](https://user-images.githubusercontent.com/59486309/185414541-80829d19-74ee-4799-8e0f-1cd9aaedee64.JPG)

**Comment by gamingoninsulin** [comment]
i was able to fix the discord error i think i installed "discord_comonents_mirror version 2.1.5"
now its not comming up but the others still do

**Comment by gamingoninsulin** [comment]
i reaad the description not carful enough i deleted the folder adn changed the requirements.txt discord.py infront of the mirror changed the discord-comonents to discord-components-mirror and its working but the onl;y thing i now need is a Slime_Server.token how do get that its saying its missing 

![missing token discord bot](https://user-images.githubusercontent.com/59486309/185423008-5ed441d0-4511-41e9-913a-544f96afd3ed.JPG)

**Comment by 0n1udra** [comment]
Did you make a bot in Discord Developer Portal? You create your bot, and get the Token from the portal and put it in the .token file, and then generate a invite link with the right permissions. 

Discord Developer Portal:
https://discord.com/developers/applications

Here's a few guides for some quick help.
https://discord.com/developers/docs/getting-started#creating-an-app
https://realpython.com/how-to-make-a-discord-bot-python/  

Also, remember to set the Privileged Gateway Intents, enable MESSAGE CONTENT INTENT.   
![Screenshot-20220818140309-1869x589](https://user-images.githubusercontent.com/15573136/185463683-0564dede-99a3-42cd-b082-408df3c3bfc5.png)

**Comment by gamingoninsulin** [comment]
I have the token but must it in token_file.token or in a .py file how does it look like 

# EXAMPLE TOKEN .PY FILE
Token = <FAKE_TOKEN> 

# EXAMPLE TOKEN TEXT FILE
EXAMPLE_TOKEN

**Comment by 0n1udra** [comment]
It's just file.token with the token pasted in it and nothing else. 

here's in example (fake token for example).
![Screenshot-20220818160722-997x233](https://user-images.githubusercontent.com/15573136/185485142-4ec5cf8b-f385-434f-a7a3-80219d9d24b3.png)
